# Generated by Django 4.0.3 on 2023-06-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_productos_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='nom_producto',
            new_name='nom_product',
        ),
    ]
